### ISSUE TITLE
Windy

### ISSUE THREAD

**Issue by Cha14ka** [MoonlightPS/MoonlightTS#7]
What is this WindyUtils? It's in the .gitignore, so I have no idea where to get it
![image](https://user-images.githubusercontent.com/16352397/218262835-617a4af9-376a-439d-95a0-01392eec284b.png)

**Comment by Thereallo1026** [comment]
Windy

**Comment by aarhuuus** [comment]
Windy

**Comment by tamilpp25** [comment]
oh I forgot to remove this, it was used to view game errors in game

**Comment by yarik0chka** [comment]
https://user-images.githubusercontent.com/64433879/218263465-ff0e8b64-5e9c-43a2-821e-7edafe6ba4e8.mp4

Windy!

**Comment by aarhuuus** [comment]
The best y'all can do to fix this is to clone the new latest commit which fixes this issue on manual TypeScript compilation.
